databases:
  - name: AnoArts_DB
    databaseName: anoarts_db
    user: AnoArts
    region: singapore

services:
  - type: web
    name: AnoArts
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AnoArts_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

